#!/bin/sh
set -ex
export DEBIAN_FRONTEND=noninteractive
dpkg --add-architecture "$1"
apt-get update
apt-get install --yes gnupg
apt-key adv --verbose --keyserver hkp://keyserver.ubuntu.com --recv-keys 'B5A08F01796E7F521861B449372D1FF271F2DD50'
echo "deb [arch=$1] http://deb.ooni.org/ unstable main" | tee /etc/apt/sources.list.d/ooniprobe.list
apt-get update
apt-get install --yes ooniprobe-cli
dpkg -l | grep ooniprobe-cli
ooniprobe onboard --yes
shift
"$@"
