description: |
  Runs a development version of probe-desktop using the version
  of the CLI configured inside probe-desktop.

pipeline:
  - command: |
      cd repo/probe-desktop && \
      yarn install && \
      yarn download:probe-cli && \
      yarn dev
