description: |
  Opens a debian-stable docker shell where the version of
  ooni/probe-cli configured in our debian repository has
  just been installed.

pipeline:
  - interactive: true
    command: |
      docker run --platform=linux/amd64 -it -v$(pwd):/ooni \
        -w/ooni debian:stable \
        ./tools/run.d/install-stable-cli-inside-debian/docker-main \
        amd64 /bin/bash
