#!/bin/bash

# Cleans the content of all repositories.

set -euo pipefail

args="$@"
branch_name=$1

source ./tools/lib.bash

do_clean() {
	local dirname=$(repo_to_dir $1)
	(
		run cd $dirname
		run git clean "$args"
	)
}

for_each_repo do_clean
