#!/bin/bash

# Cleans the content of all repositories.

set -euo pipefail

source ./tools/libgit.bash

do_clean() {
	local dirname=$(repo_to_dir $1)
	(
		run cd $dirname
		run git clean -dffx
	)
}

for_each_repo do_clean
run rm -rf ./output/*
