#!/bin/bash

# Commits into all the modified repositories.

set -euo pipefail

if [[ $# -ne 1 ]]; then
	echo "usage: $0 commit-message-file" 1>&2
	exit 1
fi
commit_message_file=$(readlink -f $1)
if [[ ! -f $commit_message_file ]]; then
	echo "fatal: $commit_message_file does not exist" 1>&2
	exit 1
fi

source ./tools/lib.bash

do_commit() {
	local dirname=$(repo_to_dir $1)
	(
		run cd $dirname
		if [[ -z $(git status -s) ]]; then
			return
		fi
		run git commit -aF $commit_message_file
	)
}

for_each_repo do_commit
