#!/bin/bash

# Shows what changed for each repository

set -euo pipefail

diff_args="$@"
if [[ $diff_args == "" ]]; then
	diff_args="--"
fi
if [[ -z ${MONOREPO_DIFF_INNER+x} ]]; then
	export MONOREPO_DIFF_INNER=1
	$0 "$diff_args" | less
	exit 0
fi

source ./tools/libgit.bash

do_show_diff() {
	dirname=$(repo_to_dir $1)
	(cd $dirname && git --no-pager diff --src-prefix=$dirname/a/ \
		--dst-prefix=$dirname/b/ --color=always $diff_args)
}

for_each_repo do_show_diff
