#!/bin/bash

# Installs the basic development environment

set -euo pipefail

platform=$(uname -s)
arch=$(uname -m)
installer=./tools/install.d/$platform-$arch.bash

if ! [[ -f $installer ]]; then
    echo "fatal: we don't support $platform-$arch yet" 1>&2
    exit 1
fi

echo "Welcome!"
echo ""
echo "This tool will check for commands that you can install"
echo "using your distribution and fail if they are not available"
echo "on your system. In such a case, please install them"
echo "using the appropriate command or commands. This tool will"
echo "also download and verify extra software that is required"
echo "by ooniprobe and whose version should be pinned."
echo ""
echo "Hit enter to continue the setup"
read

source ./tools/lib.bash
source ./tools/install.d/lib.bash
source $installer
installer_main
