#!/bin/bash

# Checks out a branch for all repositories

set -euo pipefail

if [[ $# -ne 1 ]]; then
	echo "usage: $0 branch-name" 1>&2
	exit 1
fi
branch_name=$1

source ./tools/lib.bash

do_newbranch() {
	dirname=$(repo_to_dir $1)
	(run cd $dirname && run git checkout -b $branch_name)
}

for_each_repo do_newbranch
