#!/bin/bash

# Opens VSCode for the given repository

set -euo pipefail

if [[ $# -ne 1 ]]; then
	echo "usage: $0 path-to-repo" 1>&2
	exit 1
fi
path_to_repo=$1
source ./tools/lib.bash
fail_if_main $1
code $path_to_repo 2>/dev/null
