#!/bin/bash

# Resets the status of all repositories

set -euo pipefail

if [[ $# -ne 0 ]]; then
	echo "usage: $0" 1>&2
	exit 1
fi

source ./tools/lib.bash

do_reset() {
	dirname=$(repo_to_dir $1)
	echo ""
	(run cd $dirname && run git reset --hard HEAD && run git checkout main &&
		run git branch | run grep -v main | run xargs git branch -D)
}

for_each_repo do_reset
