#!/bin/bash
set -euo pipefail

source ./config/lib.bash
source ./tools/libcore.bash

__golang_version=$(cd ./repo/probe-cli && cat GOVERSION)
__golang_tarball=go$__golang_version.$(goos)-$(goarch).tar.gz
__golang_tarball_url=https://dl.google.com/go/$__golang_tarball
__golang_sha256=$__golang_tarball.sha256
__golang_sha256_url=$__golang_tarball_url.sha256

if [[ ! -d $HOME/sdk/go$__golang_version ]]; then
	run curl -fsSLO $__golang_tarball_url
	run curl -fsSLO $__golang_sha256_url
	echo "$(cat $__golang_sha256)  $__golang_tarball" >SHA256SUMS
	run sha256sum -c SHA256SUMS
	run rm -f SHA256SUMS $__golang_sha256
	run mkdir -p $HOME/sdk
	run tar -C $HOME/sdk -xf $__golang_tarball
	run mv $HOME/sdk/go $HOME/sdk/go$__golang_version
	run rm -f $__golang_tarball
fi

export "PATH=$HOME/sdk/go$__golang_version/bin:$PATH"
require_commands go

"$@"
