#!/bin/bash

# Shows the status of each repository

set -euo pipefail

if [[ $# -ne 0 ]]; then
	echo "usage: $0" 1>&2
	exit 1
fi

source ./tools/lib.bash

do_show_status() {
	local dirname=$(repo_to_dir $1)
	local namelen=$(printf $dirname | wc -c)
	printf "[$dirname]"
	local spaces=$((24 - $namelen))
	while [[ $spaces > 0 ]]; do
		printf " "
		spaces=$(($spaces - 1))
	done
	local branch_name=$(get_branch_name $1)
	local ref=$(cd $dirname && git --no-pager log -1 --oneline)
	printf "[$branch_name] $ref\n"
	(
		cd $dirname
		git status -s
	)
}

for_each_repo do_show_status
