#!/bin/bash

# vscode opens the given repository inside vscode.

set -euo pipefail

source ./tools/libgit.bash

do_print_name() {
	printf "%s\n" "- $(repo_to_dir $1)"
}

if [[ $# -ne 1 ]]; then
	printf "This command opens the given repository inside vscode.\n"
	printf "\n"
	printf "Usage:\n"
	printf "  ./tools/vscode <repository>\n"
	printf "\n"
	printf "Available repositories:\n"
	printf "%s\n" "- ."
	for_each_repo do_print_name
	printf "\n"
	exit 0
fi

case "$(goos)" in
"linux")
	code --new-window "$(realpath $1)"
	;;
"darwin")
	open "/Applications/Visual Studio Code.app" --args --new-window "$(realpath $1)"
	;;
*)
	fatal "This command only works on Linux and Darwin"
	;;
esac
