description: |
  Builds an experimentalFullRelease of ooni/probe-android
  using an oonimkall.aar built from the current tree.

pipeline:
  - action: generate-android-keystore
  - action: setup-android
  - action: setup-go
  - action: setup-oonigo
  - action: copy-psiphon-config
  - action: build-oonimkall-android
  - action: build-android-experimental-full-release
  - action: sign-android-apk
